### ISSUE TITLE
rpc error in the last step `yarn run setup`

### ISSUE THREAD

**Issue by Pythonberg1997** [OffchainLabs/orbit-setup-script#68]
Trying to deploy a anyTrust chain on arb sepolia net.

Log:
```
yarn run v1.22.21
warning package.json: No license field
$ ts-node scripts/setup.ts
resumeState file found, will restart from where it failed last time.
Running tokenBridgeDeployment or erc20TokenBridge script to deploy token bridge contracts on parent chain and your Orbit chain 🌉🌉🌉🌉🌉
Creating token bridge for rollup 0xA22A...2189
Detected custom gas token chain with native token 0x2e3B...AF5E
Error occurred: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":60,
......
```

And there's a lot code internal that looks like the contract code.

```
), error={}, code=SERVER_ERROR, version=web/5.7.1)
      at Logger.makeError (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
      at Logger.throwError (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
      at processJsonFunc (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/src.ts/index.ts:375:24)
      at /Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/src.ts/index.ts:320:42
      at step (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.throw (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:14:53)
      at rejected (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:6:65)
      at processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'invalid JSON',
    code: 'SERVER_ERROR',
    body: Uint8Array(7949) [
      123, 34, 106, 115, 111, 110, 114, 112,  99, 34,  58,  34,
       50, 46,  48,  34,  44,  34, 105, 100,  34, 58,  54,  48,
       44, 34, 114, 101, 115, 117, 108, 116,  34, 58,  34,  48,
      120, 54,  48,  56,  48,  54,  48,  52,  48, 53,  50,  54,
       48, 48,  52,  51,  54,  49,  48,  54,  49, 48,  49,  52,
      102, 53,  55,  54,  48,  48,  48,  51,  53, 54,  48, 101,
       48, 49,  99,  56,  48,  54,  51,  55, 101, 99, 101,  98,
      101, 48,  48,  49,  49,  54,  49,  48,  48, 98,  54,  53,
       55, 56,  48,  54,
      ... 7849 more items
    ],
    error: SyntaxError: Unexpected end of JSON input
        at JSON.parse (<anonymous>)
        at processJsonFunc (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/src.ts/index.ts:373:31)
        at /Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/src.ts/index.ts:320:42
        at step (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.throw (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:14:53)
        at rejected (/Users/Projects/orbit-setup-script/node_modules/@ethersproject/web/lib/index.js:6:65)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
  },
  requestBody: '{"method":"eth_getCode","params":["0xf78c950a5e65091367a602bd1a40dc3ab80240d6","latest"],"id":60,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  url: 'https://sepolia-rollup.arbitrum.io/rpc'
}
Seems something went wrong during this process, but don't worry, we have recorded the deployed and initialized contracts into ./config/resumeState.json, next time you rerun the script, it will restart from where it failed 
Done in 19.98s.
```

**Comment by gitoutoftown** [comment]
Not getting the same error. but getting "/bin/sh: ts-node: command not found". ran the run script command from root of repo and script folder just to see. no luck.
<img width="795" alt="Screen Shot 2024-03-07 at 9 23 09 PM" src="https://github.com/OffchainLabs/orbit-setup-script/assets/45711456/874ef589-64a9-4058-9241-fdfb0a5c6b13">

**Comment by gitoutoftown** [comment]
Disregard... ran wrong node version
